config/routes.rb
IpfOsascoAvaliacao2011::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'evaluation#index'
  match "autenticar", :to => 'evaluation#authenticate'
  match "confirmar", :to => 'evaluation#confirm'
  match "identificar", :to => 'evaluation#identify'
  match "instrucoes", :to => 'evaluation#instructions'
  match "responder_dimensao", :to => 'evaluation#answerdimension'
  match "revisar", :to => 'evaluation#review'
  match "validar_revisao", :to => 'evaluation#checkreview'
  match "salvar", :to => 'evaluation#save'
  match "lista_presenca", :to => 'evaluation#presence_list'
  match "salvar_lista_presenca", :to => 'evaluation#save_presence_list'
  match "gabarito", :to => 'evaluation#evaluation_template', :as => 'template'

  match "passwords/generate_all_letters", :to => 'passwords#generate_all_letters'
  match "passwords/generate_creche_conveniadas_letters", :to => 'passwords#generate_creche_conveniadas_letters'
  match "passwords/generate_all_passwords", :to => 'passwords#generate_all_passwords'
  match "admin/passwords/:id/download_letter", :to => 'admin_passwords#download_letter'

  match "mapa", :to => 'complex_queries#map_table', :as => 'map'
  match "sistema/respostas/gerar_estatisticas", :to => 'system#generate_answer_stats', :as => 'generate_answer_stats'
  match "sistema/senhas/gerar", :to => 'system#generate_passwords', :as => 'generate_passwords'
  match "sistema/instrumental/importar", :to => 'system#import_instrument', :as => 'import_instrument'
  match "sistema/niveis_de_servico/importar", :to => 'system#import_service_levels', :as => 'import_service_levels'
  match "sistema/escolas/importar", :to => 'system#import_schools', :as => 'import_schools'
  match "sistema/dimensoes/importar", :to => 'system#import_dimensions', :as => 'import_dimensions'
  match "sistema/segmentos/importar", :to => 'system#import_segments', :as => 'import_segments'
  match "sistema/indicadores/importar", :to => 'system#import_indicators', :as => 'import_indicators'
  
  
  

  resources :evaluation do
    get :autocomplete_school_name, :on => :collection
  end
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  belongs_to :service_level
  has_many :question_text
  has_many :passwords
  has_many :answers
  has_many :practices
  has_many :dimension_statuses
  has_many :presence
  has_many :evaluation_answer_stats
  has_many :answer_logs

  begin
    ServiceLevel.all.each do |sl|
      scope sl.name, where("service_level_id = ?", sl.id)
    end
  rescue
  end

end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  # GET /segments
  # GET /segments.xml
  def index
    @segments = Segment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @segments }
    end
  end

  # GET /segments/1
  # GET /segments/1.xml
  def show
    @segment = Segment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @segment }
    end
  end

  # GET /segments/new
  # GET /segments/new.xml
  def new
    @segment = Segment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @segment }
    end
  end

  # GET /segments/1/edit
  def edit
    @segment = Segment.find(params[:id])
  end

  # POST /segments
  # POST /segments.xml
  def create
    @segment = Segment.new(params[:segment])

    respond_to do |format|
      if @segment.save
        format.html { redirect_to(@segment, :notice => 'Segment was successfully created.') }
        format.xml  { render :xml => @segment, :status => :created, :location => @segment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @segment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /segments/1
  # PUT /segments/1.xml
  def update
    @segment = Segment.find(params[:id])

    respond_to do |format|
      if @segment.update_attributes(params[:segment])
        format.html { redirect_to(@segment, :notice => 'Segment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @segment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.xml
  def destroy
    @segment = Segment.find(params[:id])
    @segment.destroy

    respond_to do |format|
      format.html { redirect_to(segments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/edit.html.erb
<h1>Editing segment</h1>

<% form_for(@segment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @segment %> |
<%= link_to 'Back', segments_path %>

app/views/segments/index.html.erb
<h1>Listing segments</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @segments.each do |segment| %>
  <tr>
    <td><%=h segment.name %></td>
    <td><%= link_to 'Show', segment %></td>
    <td><%= link_to 'Edit', edit_segment_path(segment) %></td>
    <td><%= link_to 'Destroy', segment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New segment', new_segment_path %>

app/views/segments/new.html.erb
<h1>New segment</h1>

<% form_for(@segment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', segments_path %>

app/views/segments/show.html.erb
<p>
  <b>Name:</b>
  <%=h @segment.name %>
</p>


<%= link_to 'Edit', edit_segment_path(@segment) %> |
<%= link_to 'Back', segments_path %>